params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema. 
  title: "后现代主义生活黑客 \U0001F4DA"
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://jiayezheng.tech/images/sl.png"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link resources/_gen/images/dio.webp>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "具体问题，具体分析是马克思主义活的灵魂"
    icon: "https://jiayezheng.tech/images/sl.png" 
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    Title: "名声，只是一种糟糕的错觉 \U0001F4DA"
    subtitle: "Computer Science is no more about computers than astronomy is about telescopes.<br>
——— E. W. Dijkstra"
    imageUrl: "https://jiayezheng.tech/images/sl.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: noobi's image 
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    #Title: "Hi there \U0001F44B"
    Title: "名声，只是一种糟糕的错觉 \U0001F4DA"
    Content: "Computer Science is no more about computers than astronomy is about telescopes.<br>
——— E. W. Dijkstra"

  socialIcons:
    # - name: twitter
    #   url: "https://twitter.com/"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/14439276/peg-noobi"
    - name: github
      url: "https://github.com/Xpectuer"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/Xpectuer/my-blog/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: About Me
      name: 关于我
      url: /aboutme/
      weight: 10
    - identifier: tags
      name: 标签
      url: /tags/
      weight: 20
    - identifier: home
      name: 主页
      url: https://jiayezheng.tech/
      weight: 30

markup:
  goldmark:
    renderer:
      unsafe: true

