baseURL: "https://xpectuer.github.io/blog-of-noobi"
title: "苟利国家生死以，岂因祸福避趋之"
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45



minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema. 
  title: "后现代主义生活黑客 \U0001F4DA"
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "images/sl.png"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link resources/_gen/images/dio.webp url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "具体问题，具体分析是马克思主义活的灵魂"
    icon: "/images/sl.png" 
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    Title: "后现代主义生活黑客 \U0001F4DA"
    subtitle: "计算机科学，准确地来说，并不是一门科学，它甚至与计算机本身无关。
  <br/> 这是一门源于工程、数学与艺术，用于解决复杂问题的学科，是一门值得修炼的真功夫。"
    imageUrl: "images/sl.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: noobi's image 
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    #Title: "Hi there \U0001F44B"
    Title: "后现代主义生活黑客 \U0001F4DA"
    Content: "本人爱好广泛：包括但不限于哲学、数学、计算机科学、经济学。不定期更新：算法导论带读、读书笔记分享。"

  socialIcons:
    - name: twitter
      url: "https://twitter.com/"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/14439276/peg-noobi"
    - name: github
      url: "https://github.com/Xpectuer"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: categories
      name: 分类
      url: /categories/
      weight: 10
    - identifier: tags
      name: 标签
      url: /tags/
      weight: 20
    - identifier: url
      name: noobi.github.io
      url: https://xpectuer.github.io/
      weight: 30


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

