baseURL: "http://jiayezheng.tech/my-blog/"
#baseURL: "http://xpectuer.github.io/my-blog/"
#baseURL: "http://localhost:1313/my-blog/"
title: "苟利国家生死以，岂因祸福避趋之"
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# staticDir: true

googleAnalytics: UA-123-45


minify:
  disableXML: true
  minifyOutput: true

